version: "3"

services:
  influxdb-v2:
    image: influxdb:2.5
    container_name: influxdb
    hostname: influxdb
    env_file:
      - influxdb-v2.env
    volumes:
      - influxdb-v2:/var/lib/influxdb2:rw
    ports:
      - 8086:8086
    restart: unless-stopped

  telegraf-proxy:
    image: telegraf:1.24.4
    container_name: telegraf-proxy
    hostname: telegraf-proxy
    volumes:
      - ./telegraf-proxy/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - ./influxdb-v2.env
    ports:
      - 8088:8088 # Same as ./telegraf-proxy/telegraf.conf [[inputs.influxdb_v2_listener]]
    depends_on:
      - influxdb-v2
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.3.1
    container_name: grafana
    hostname: grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-storage:/var/lib/grafana:rw
      - ./grafana/etc/dashboards:/etc/dashboards:ro
    env_file:
      - ./influxdb-v2.env
    ports:
      - 3000:3000
    depends_on:
      - influxdb-v2
    restart: unless-stopped

volumes:
  influxdb-v2:
  grafana-storage: