version: "3"

services:
  influxdb-v2:
    image: influxdb:2.5
    container_name: ${INFLUXDB_HOST}
    hostname: ${INFLUXDB_HOST}
    env_file:
      - ./.env
    volumes:
      - influxdb-v2:/var/lib/influxdb2:rw
      - ./influxdb-v2/scripts:/docker-entrypoint-initdb.d:ro
    ports:
      - ${INFLUXDB_PORT}:8086
    restart: unless-stopped

  telegraf-proxy:
    image: telegraf:1.24.4
    container_name: telegraf-proxy
    hostname: telegraf-proxy
    user: telegraf:${PROXY_USER_ID}
    volumes:
      - ./telegraf-proxy/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
    environment:
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs
      HOST_HOSTNAME: ${HOSTNAME}
    env_file:
      - ./.env
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}
    depends_on:
      - influxdb-v2
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.3.1
    container_name: grafana
    hostname: grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-storage:/var/lib/grafana:rw
      - ./grafana/etc/dashboards:/etc/dashboards:ro
    env_file:
      - ./.env
    ports:
      - ${GRAFANA_PORT}:3000
    depends_on:
      - influxdb-v2
    restart: unless-stopped

volumes:
  influxdb-v2:
  grafana-storage: