apiVersion: 1

datasources:
  - name: ${INFLUXDB_HOST}
    type: influxdb
    access: proxy
    url: http://${INFLUXDB_HOST}:8086
    jsonData:
      version: Flux
      organization: ${DOCKER_INFLUXDB_INIT_ORG}
      defaultBucket: ${DOCKER_INFLUXDB_INIT_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}